<?php
/**
 * Ask AI 1 question and interpretation-review panel.
 *
 * @package EhrmanBlogDiscovery
 */

namespace EhrmanBlogDiscovery;

$ehrman_blog_discovery_id            = Database::text( $ehrman_blog_discovery_context['id'] ?? '' );
$ehrman_blog_discovery_question      = Database::text( $ehrman_blog_discovery_context['question'] ?? '' );
$ehrman_blog_discovery_action        = Database::text( $ehrman_blog_discovery_context['action'] ?? '' );
$ehrman_blog_discovery_sort_options  = Database::text( $ehrman_blog_discovery_context['sort_options'] ?? '' );
$ehrman_blog_discovery_ai_configured = true === ( $ehrman_blog_discovery_context['ai_configured'] ?? false );
?>
<form class="ebd-question-panel" action="<?php echo esc_url( $ehrman_blog_discovery_action ); ?>" method="get" data-ebd-question-form>
	<input type="hidden" name="ebd_ai_request" value="" data-ebd-ai-request>
	<div id="<?php echo esc_attr( $ehrman_blog_discovery_id ); ?>-controls" data-ebd-question-expanded>
		<label for="<?php echo esc_attr( $ehrman_blog_discovery_id ); ?>"><strong><?php echo esc_html__( 'What would you like to explore?', 'ehrman-blog-discovery' ); ?></strong></label>
		<p class="ebd-question-help"><?php echo esc_html__( 'Ask a question or describe what you want to find. AI will find related posts on Bart\'s blog for you to review.', 'ehrman-blog-discovery' ); ?></p>
		<textarea id="<?php echo esc_attr( $ehrman_blog_discovery_id ); ?>" name="ebd_question" rows="3" maxlength="800" required placeholder="<?php echo esc_attr__( 'Example: How do the teachings of Paul differ from those of Jesus?', 'ehrman-blog-discovery' ); ?>" data-ebd-question-input><?php echo esc_textarea( $ehrman_blog_discovery_question ); ?></textarea>
		<div class="ebd-question-actions">
			<button type="button" class="ebd-question-interpret" data-ebd-question-interpret<?php echo $ehrman_blog_discovery_ai_configured ? '' : ' disabled'; ?>><?php echo esc_html__( 'Submit', 'ehrman-blog-discovery' ); ?></button>
			<button type="button" class="ebd-question-clear" data-ebd-question-clear><?php echo esc_html__( 'Clear', 'ehrman-blog-discovery' ); ?></button>
		</div>
		<?php if ( ! $ehrman_blog_discovery_ai_configured ) : ?>
			<p class="ebd-question-configuration"><?php echo esc_html__( 'Local AI credentials must be configured before questions can be interpreted.', 'ehrman-blog-discovery' ); ?></p>
		<?php endif; ?>
		<p class="ebd-question-status" data-ebd-question-status aria-live="polite"></p>
		<section class="ebd-question-review" data-ebd-question-review hidden>
			<h3><?php echo esc_html__( 'Review the interpreted search', 'ehrman-blog-discovery' ); ?></h3>
			<p><?php echo esc_html__( 'These are the topics and keywords selected from your question. Remove any that do not reflect what you intended.', 'ehrman-blog-discovery' ); ?></p>
			<ul data-ebd-question-terms></ul>
			<div class="ebd-sort-row"><span><?php echo esc_html__( 'Sort by', 'ehrman-blog-discovery' ); ?></span><?php echo $ehrman_blog_discovery_sort_options; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the renderer from fixed labels and escaped attributes. ?></div>
			<div class="ebd-question-actions"><button type="submit" class="ebd-question-search" data-ebd-question-search disabled><?php echo esc_html__( 'Search posts', 'ehrman-blog-discovery' ); ?></button></div>
		</section>
	</div>
</form>
