<?php
/**
 * Ask AI 2 semantic-question panel.
 *
 * @package EhrmanBlogDiscovery
 */

namespace EhrmanBlogDiscovery;

$ehrman_blog_discovery_id           = Database::text( $ehrman_blog_discovery_context['id'] ?? '' );
$ehrman_blog_discovery_question     = Database::text( $ehrman_blog_discovery_context['question'] ?? '' );
$ehrman_blog_discovery_action       = Database::text( $ehrman_blog_discovery_context['action'] ?? '' );
$ehrman_blog_discovery_sort_options = Database::text( $ehrman_blog_discovery_context['sort_options'] ?? '' );
$ehrman_blog_discovery_message      = Database::text( $ehrman_blog_discovery_context['message'] ?? '' );
$ehrman_blog_discovery_configured   = true === ( $ehrman_blog_discovery_context['configured'] ?? false );
?>
<form class="ebd-question-panel ebd-semantic-panel" action="<?php echo esc_url( $ehrman_blog_discovery_action ); ?>" method="get" data-ebd-semantic-form<?php echo '' !== trim( $ehrman_blog_discovery_question ) ? ' data-ebd-auto-run="true"' : ''; ?>>
	<input type="hidden" name="ebd_ai_request" value="" data-ebd-ai-request>
	<label for="<?php echo esc_attr( $ehrman_blog_discovery_id ); ?>"><strong><?php echo esc_html__( 'What would you like to explore?', 'ehrman-blog-discovery' ); ?></strong></label>
	<p class="ebd-question-help"><?php echo esc_html__( 'Ask a question or describe what you want to find. AI will find related posts on Bart\'s blog for you to review.', 'ehrman-blog-discovery' ); ?></p>
	<textarea id="<?php echo esc_attr( $ehrman_blog_discovery_id ); ?>" name="ebd_question" rows="3" maxlength="800" required placeholder="<?php echo esc_attr__( 'Example: How does Luke change Mark?', 'ehrman-blog-discovery' ); ?>" data-ebd-semantic-question><?php echo esc_textarea( $ehrman_blog_discovery_question ); ?></textarea>
	<div class="ebd-question-actions">
		<button type="submit" class="ebd-question-interpret" data-ebd-semantic-submit<?php echo $ehrman_blog_discovery_configured ? '' : ' disabled'; ?>><?php echo esc_html__( 'Submit', 'ehrman-blog-discovery' ); ?></button>
		<button type="button" class="ebd-question-clear" data-ebd-semantic-clear><?php echo esc_html__( 'Clear', 'ehrman-blog-discovery' ); ?></button>
	</div>
	<?php if ( '' !== $ehrman_blog_discovery_message ) : ?>
		<p class="ebd-question-configuration"><?php echo esc_html( $ehrman_blog_discovery_message ); ?></p>
	<?php endif; ?>
	<p class="ebd-question-status" data-ebd-semantic-status aria-live="polite"></p>
	<div class="ebd-sort-row ebd-semantic-sort"><span><?php echo esc_html__( 'Sort by', 'ehrman-blog-discovery' ); ?></span><?php echo $ehrman_blog_discovery_sort_options; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by the renderer from fixed labels and escaped attributes. ?></div>
</form>
